from MainGUI import MainGUI

CANVAS_WIDTH = 750
CANVAS_HEIGHT = 750
CELL_COUNT_X = 50
CELL_COUNT_Y = 50
MAX_FOOD = 4
MAX_NESTS = 4

MainGUI(
    CANVAS_WIDTH,
    CANVAS_HEIGHT,
    CELL_COUNT_X,
    CELL_COUNT_Y,
    MAX_FOOD,
    MAX_NESTS)
